export * from './about/about.component'
export * from './experience/experience.component'
export * from './education/education.component'
export * from './skills/skills.component'
export * from './references/references.component'
export * from './contact/contact.component'
export * from './projects/projects.component'
export * from './loader/loader.component'